# Site Info
title: Taejin KIM
tagline: 'Taejin Kim BLOG'
description: '웹, 보안, 알고리즘에 관심이 많은 초보 개발자'
baseurl: ""
url: http://kimtaejin3/github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Taejin KIM
  description: 웹, 보안, 알고리즘에 관심이 많은 초보 개발자
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    github:    https://github.com/kimtaejin3
    facebook:  https://www.facebook.com/profile.php?id=100040682680379
    #email: rlaxowls1316@naver.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://kimtaejin3.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/nhn.png
  caption: NHN; 

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

